### ISSUE TITLE
No module named wda

### ISSUE THREAD

**Issue by Jenner4S** [Prinsphield/Wechat_AutoJump#103]
python nn_play.py --phone IOS --sensitivity 2.045                                                                                                       master [791cc49] modified
2018-01-26 14:50:32.281695: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
==== successfully restored ====
Traceback (most recent call last):
  File "nn_play.py", line 209, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 50, in __init__
    import wda
ImportError: No module named wda

我的环境是 ip6sp
wda也按您的说明去部署了，报No module named wda。

**Comment by Jenner4S** [comment]
问题已解决！pip install --pre facebook-wda;
程序已经正常运行了！就是跳的太准了！感谢分享！
