### ISSUE TITLE
python tra in.py 出错

### ISSUE THREAD

**Issue by zkailinzhang** [Prinsphield/Wechat_AutoJump#110]
E:\python\weixin\Wechat_AutoJump\cnn_coarse_to_fine\config\base.large>python tra
in.py
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    dataset = JumpData()
  File "../..\data_provider\jump_data.py", line 10, in __init__
    self.get_name_list()
  File "../..\data_provider\jump_data.py", line 32, in get_name_list
    self.name_list = list(filter(_name_checker, self.name_list))
  File "../..\data_provider\jump_data.py", line 25, in _name_checker
    posi = name.index('_res')
ValueError: substring not found

**Comment by zkailinzhang** [comment]
数据的路径问题，我把数据放到Resources目录下了，，，把Data文件夹放到wechat autojump目录下，就可以了
