### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by zhangyouchang** [Prinsphield/Wechat_AutoJump#18]
控制台运行程序后出现报错：
YydeMacBook-Pro:~ yyzhang$ python /Users/yyzhang/Desktop/Wechat_AutoJump-master/model.py --phone IOS --sensitivity 2.045
Traceback (most recent call last):
  File "/Users/yyzhang/Desktop/Wechat_AutoJump-master/model.py", line 65, in <module>
    out = model.forward(tf.zeros((1, 640, 720, 3)))
TypeError: forward() missing 2 required positional arguments: 'is_training' and 'keep_prob'
请问该如何处理？

**Comment by zhangyouchang** [comment]
我这个应该是没有下载训练模型，等下载好跑一边在回复结果～

**Comment by Prinsphield** [comment]
你跑错文件了，是`python nn_play.py`

**Comment by zhangyouchang** [comment]
@Prinsphield 请问下载好模型后这一步怎么做呀：and then modify self.data_dir in those files under cnn_coarse_to_fine/data_provider directory.

**Comment by zhangyouchang** [comment]
@Prinsphield 我把train log文件放在resource文件夹下，在控制台跑命令后报错如下：InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
	 [[Node: save/RestoreV2_29 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_29/tensor_names, save/RestoreV2_29/shape_and_slices)]]

**Comment by zhangyouchang** [comment]
@Prinsphield 以下是全部信息，请帮忙看下有什么问题，多谢啦～
YydeMacBook-Pro:~ yyzhang$ python /Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py --phone IOS --sensitivity 2.045
2018-01-05 21:34:41.035555: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-05 21:34:41.035586: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-05 21:34:41.035591: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-05 21:34:41.035595: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-05 21:34:41.035599: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:From /Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py:72: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
2018-01-05 21:34:42.782369: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.782369: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.782381: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.782381: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.782933: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.782956: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.782990: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783087: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783141: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783175: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783269: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783294: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783346: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783395: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783418: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783475: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783495: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783534: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783555: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783571: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783589: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783605: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783695: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783714: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783739: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783764: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783776: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783792: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783861: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
2018-01-05 21:34:42.783898: W tensorflow/core/framework/op_kernel.cc:1152] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/Applications/anaconda/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
	 [[Node: save/RestoreV2_29 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_29/tensor_names, save/RestoreV2_29/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py", line 205, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.debug, args.resource)
  File "/Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py", line 48, in __init__
    self.load_resource()
  File "/Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py", line 77, in load_resource
    self.saver_coarse.restore(self.sess, self.ckpt)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
	 [[Node: save/RestoreV2_29 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_29/tensor_names, save/RestoreV2_29/shape_and_slices)]]

Caused by op 'save/RestoreV2_29', defined at:
  File "/Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py", line 205, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.debug, args.resource)
  File "/Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py", line 48, in __init__
    self.load_resource()
  File "/Users/yyzhang/Desktop/Wechat_AutoJump-master/nn_play.py", line 75, in load_resource
    self.saver_coarse = tf.train.Saver(var_coarse)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Applications/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse
	 [[Node: save/RestoreV2_29 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_29/tensor_names, save/RestoreV2_29/shape_and_slices)]]

YydeMacBook-Pro:~ yyzhang$

**Comment by pkuanjie** [comment]
你可以检查一下是不是train_logs_coarse和train_log_fine两个文件夹放在了resource文件夹下

**Comment by zhangyouchang** [comment]
@Richard-An 还是这个问题，但是我已经把两个文件都放在resource文件夹下了
![image](https://user-images.githubusercontent.com/33805809/34615815-178d0e0a-f271-11e7-98c3-c4865a4a17cc.png)

**Comment by pkuanjie** [comment]
我猜测是tf的版本问题……我这边训练和测试机器tf是1.0.1
