### ISSUE TITLE
nn_play报错

### ISSUE THREAD

**Issue by silverbulletmdc** [Prinsphield/Wechat_AutoJump#23]
我将你们的模型文件下载解压后放到resource文件夹里。读取模型时发生报错
```
Traceback (most recent call last):
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Users\lenovo\Anaconda3\lib\contextlib.py", line 89, in __exit__
    next(self.gen)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/project/Wechat_AutoJump/nn_play.py", line 204, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.debug, args.resource)
  File "D:/project/Wechat_AutoJump/nn_play.py", line 47, in __init__
    self.load_resource()
  File "D:/project/Wechat_AutoJump/nn_play.py", line 77, in load_resource
    self.saver_fine.restore(self.sess, self.ckpt_fine)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: not an sstable (bad magic number)
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]

Caused by op 'save_1/RestoreV2', defined at:
  File "D:/project/Wechat_AutoJump/nn_play.py", line 204, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.debug, args.resource)
  File "D:/project/Wechat_AutoJump/nn_play.py", line 47, in __init__
    self.load_resource()
  File "D:/project/Wechat_AutoJump/nn_play.py", line 75, in load_resource
    self.saver_fine = tf.train.Saver(var_fine)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1140, in __init__
    self.build()
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1172, in build
    filename=self._filename)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 688, in build
    restore_sequentially, reshape)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\lenovo\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

DataLossError (see above for traceback): not an sstable (bad magic number)
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]


Process finished with exit code 1
```

我使用的tf版本是1.3.0，Python3.6，Windows10环境运行。

**Comment by zhangyouchang** [comment]
请问必须要下载网盘里的训练文件吗？

**Comment by Prinsphield** [comment]
@zhangyouchang 可以不用自己训练，但是如果要跑，需要下载训练好的模型。

**Comment by zhangyouchang** [comment]
@Prinsphield 感谢！再请教一下：下载训练好的模型是下data.tar这个文件吗？

**Comment by Prinsphield** [comment]
@zhangyouchang 训好的文件是`train_logs.zip`

**Comment by zhangyouchang** [comment]
@Prinsphield 请问只需要下载train_logs.zip还是data.tar也需要下载？

**Comment by Prinsphield** [comment]
@zhangyouchang 只要跑一下我们训练好的只需要train_logs.zip，如果需要自己训练就要data.tar

**Comment by zhangyouchang** [comment]
@Prinsphield get it and many thanks

**Comment by silverbulletmdc** [comment]
我下载的是Google Drive里的文件，在Ubuntu16.04 Python3.6 tensorflow1.4.0上出现了同样问题。

![2018-01-05 21-24-19](https://user-images.githubusercontent.com/11981375/34611130-32a9d2de-f25f-11e7-9332-4ff3d9931ab6.png)

**Comment by pkuanjie** [comment]
你可以检查一下是不是 train_logs_coarse和train_log_fine两个文件夹放在了resource下面

**Comment by silverbulletmdc** [comment]
@Richard-An 是的

**Comment by jalllychun** [comment]
@Prinsphield 如果我想从头训练一遍网络，正确的姿势是怎样的呢？

**Comment by Prinsphield** [comment]
@jalllychun https://github.com/Prinsphield/Wechat_AutoJump/blob/master/readme_cn.md

请看readme
