### ISSUE TITLE
iphone x 不可以吗

### ISSUE THREAD

**Issue by LvJianfeng** [Prinsphield/Wechat_AutoJump#41]
```python
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/resize.cpp, line 4044
```

**Comment by Prinsphield** [comment]
可以的，是你运行的姿势可能不对或者环境没有配置好，程序没有获取到截图。

**Comment by LvJianfeng** [comment]
用的play.py
```python
python play.py --phone IOS --sensitivity 2.045
```

**Comment by Prinsphield** [comment]
你确保requirements里的东西你都安装好了

**Comment by LvJianfeng** [comment]
648 016 240   
cz89r6

**Comment by LvJianfeng** [comment]
可以了 哈哈哈

**Comment by Prinsphield** [comment]
👌，ios推荐使用`nn_play.py`

**Comment by LvJianfeng** [comment]
好的  我也发现跳不准

**Comment by Prinsphield** [comment]
iphoneX的分辨率不太一样，multiscale search容易受到影响，nn的话会好很多，另外那个sensitivity系数也需要调的。

**Comment by LvJianfeng** [comment]
请教一下 你这个怎么安装的 tensorflow  我用的pycharm来安装，启动你的nn_play出错
```ruby
 I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
WARNING:tensorflow:From nn_play.py:72: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
```

**Comment by Prinsphield** [comment]
这是warning吧，忽略

**Comment by LvJianfeng** [comment]
不行呢
```ruby
Traceback (most recent call last):
  File "nn_play.py", line 209, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 48, in __init__
    self.load_resource()
  File "nn_play.py", line 77, in load_resource
    self.saver_coarse.restore(self.sess, self.ckpt)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Library/Python/2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]

Caused by op u'save/RestoreV2_7', defined at:
  File "nn_play.py", line 209, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 48, in __init__
    self.load_resource()
  File "nn_play.py", line 75, in load_resource
    self.saver_coarse = tf.train.Saver(var_coarse)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Library/Python/2.7/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/Library/Python/2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
	 [[Node: save/RestoreV2_7 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_7/tensor_names, save/RestoreV2_7/shape_and_slices)]]
```

**Comment by Prinsphield** [comment]
看说明https://github.com/Prinsphield/Wechat_AutoJump/blob/master/readme_cn.md
需要下载训好的模型。

**Comment by LvJianfeng** [comment]
喔喔  好的，我下载下，谢谢大神了
