### ISSUE TITLE
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area

### ISSUE THREAD

**Issue by ruicky** [Prinsphield/Wechat_AutoJump#43]
设备：MAC + iphone6 10.3.1
你好当我运行
```
python3 nn_play.py --phone IOS --sensitivity 2.045
```
报错如下：

``` shell
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2018-01-08 12:44:41.128269: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
WARNING:tensorflow:From nn_play.py:72: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
==== successfully restored ====
Traceback (most recent call last):
  File "nn_play.py", line 210, in <module>
    AI.run()
  File "nn_play.py", line 195, in run
    self.play()
  File "nn_play.py", line 174, in play
    self.state = self.get_current_state()
  File "nn_play.py", line 86, in get_current_state
    self.client.screenshot('state.png')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 295, in screenshot
    value = self.http.get('screenshot').value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 101, in fetch
    return self._fetch_no_alert(method, url, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 107, in _fetch_no_alert
    return httpdo(target_url, method, data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/wda/__init__.py", line 83, in httpdo
    raise WDAError(r.status, r.value)
wda.WDAError: WDAError(status=13, value=To screenshot a frame, it must have non-0 area.

(
	0   CoreFoundation                      0x0000000183d92ff0 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001827f4538 objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183d92eac <redacted> + 0
	3   Foundation                          0x000000018482a710 <redacted> + 112
	4   XCTest                              0x000000010017406c -[XCUIScreen _screenshotDataForQuality:rect:error:] + 192
	5   XCTest                              0x0000000100173f38 -[XCUIScreen screenshotDataForQuality:rect:error:] + 108
	6   WebDriverAgentLib                   0x0000000101d87250 -[XCUIDevice(FBHelpers) fb_screenshotWithError:] + 624
	7   WebDriverAgentLib                   0x0000000101d68d30 +[FBScreenshotCommands handleGetScreenshot:] + 132
	8   WebDriverAgentLib                   0x0000000101d75984 -[FBRoute_TargetAction mountRequest:intoResponse:] + 208
	9   WebDriverAgentLib                   0x0000000101d6d5b0 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 496
	10  RoutingHTTPServer                   0x0000000101e263cc -[RoutingHTTPServer handleRoute:withRequest:response:] + 144
	11  RoutingHTTPServer                   0x0000000101e26b80 __72-[RoutingHTTPServer routeMethod:withPath:parameters:request:connection:]_block_invoke + 44
	12  libdispatch.dylib                   0x0000000182c4a9a0 <redacted> + 16
	13  libdispatch.dylib                   0x0000000182c5b7a8 <redacted> + 304
	14  libdispatch.dylib                   0x0000000182c4a9a0 <redacted> + 16
	15  libdispatch.dylib                   0x0000000182c4f5e8 _dispatch_main_queue_callback_4CF + 996
	16  CoreFoundation                      0x0000000183d410c0 <redacted> + 12
	17  CoreFoundation                      0x0000000183d3ecdc <redacted> + 1572
	18  CoreFoundation                      0x0000000183c6ed94 CFRunLoopRunSpecific + 424
	19  Foundation                          0x0000000184788d64 <redacted> + 304
	20  WebDriverAgentLib                   0x0000000101d6c5a4 -[FBWebServer startServing] + 424
	21  WebDriverAgentRunner                0x0000000101d5bbe4 -[UITestingUITests testRunner] + 132
	22  CoreFoundation                      0x0000000183d98e80 <redacted> + 144
	23  CoreFoundation                      0x0000000183c8e2b4 <redacted> + 292
	24  XCTest                              0x000000010015e654 __24-[XCTestCase invokeTest]_block_invoke.275 + 48
	25  XCTest                              0x00000001001ac208 -[XCTMemoryChecker _assertInvalidObjectsDeallocatedAfterScope:] + 56
	26  XCTest                              0x000000010015e404 __24-[XCTestCase invokeTest]_block_invoke + 680
	27  XCTest                              0x00000001001a49d8 -[XCUITestContext performInScope:] + 208
	28  XCTest                              0x000000010015e14c -[XCTestCase invokeTest] + 136
	29  XCTest                              0x000000010015f224 __26-[XCTestCase performTest:]_block_invoke.382 + 48
	30  XCTest                              0x00000001001a9a78 +[XCTContext runInContextForTestCase:block:] + 164
	31  XCTest                              0x000000010015ec20 -[XCTestCase performTest:] + 596
	32  XCTest                              0x000000010015ae14 __27-[XCTestSuite performTest:]_block_invoke + 288
	33  XCTest                              0x000000010015a83c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	34  XCTest                              0x000000010015aa4c -[XCTestSuite performTest:] + 236
	35  XCTest                              0x000000010015ae14 __27-[XCTestSuite performTest:]_block_invoke + 288
	36  XCTest                              0x000000010015a83c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	37  XCTest                              0x000000010015aa4c -[XCTestSuite performTest:] + 236
	38  XCTest                              0x000000010015ae14 __27-[XCTestSuite performTest:]_block_invoke + 288
	39  XCTest                              0x000000010015a83c -[XCTestSuite _performProtectedSectionForTest:testSection:] + 44
	40  XCTest                              0x000000010015aa4c -[XCTestSuite performTest:] + 236
	41  XCTest                              0x00000001001b3484 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 44
	42  XCTest                              0x000000010016d994 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 420
	43  XCTest                              0x00000001001b3300 -[XCTTestRunSession runTestsAndReturnError:] + 292
	44  XCTest                              0x000000010014a3d4 -[XCTestDriver runTestsAndReturnError:] + 312
	45  XCTest                              0x00000001001a8c20 _XCTestMain + 620
	46  CoreFoundation                      0x0000000183d41304 <redacted> + 20
	47  CoreFoundation                      0x0000000183d40b20 <redacted> + 288
	48  CoreFoundation                      0x0000000183d3e990 <redacted> + 728
	49  CoreFoundation                      0x0000000183c6ed94 CFRunLoopRunSpecific + 424
	50  GraphicsServices                    0x00000001856d8074 GSEventRunModal + 100
	51  UIKit                               0x0000000189f27130 UIApplicationMain + 208
	52  WebDriverAgentRunner-Runner         0x000000010006c444 WebDriverAgentRunner-Runner + 33860
	53  libdyld.dylib                       0x0000000182c7d59c <redacted> + 4
))
```

希望能帮我解决一下问题

**Comment by Prinsphield** [comment]
请问你安装了requirements吗

**Comment by ruicky** [comment]
@Prinsphield  依赖我都安装了 Opencv3 Tensorflow wda

**Comment by pkuanjie** [comment]
请问有运行iproxy吗？

**Comment by ruicky** [comment]
@Richard-An  ` iproxy 8100 8100 ` 在运行中。访问`http://127.0.0.1:8100/inspector`也正常。

**Comment by ruicky** [comment]
最后 重写的 配置好后， 全部停止，重新按照顺序启动 好了。。。囧。故close了。

**Comment by finnome** [comment]
@ruicky 
请问怎么解决。我也是遇到了这个问题。
执行顺序是什么？

**Comment by leon332157** [comment]
@pcwang0205 你ios什么版本

**Comment by pcwang0205** [comment]
iPhone 7  10.1.1？需要iOS 11？

**Comment by finnome** [comment]
iPhone 7 10.1.1？需要iOS 11？@leon332157

**Comment by leon332157** [comment]
@pcwang0205 我不確定，但是這個錯誤之前看到过，就是因为ios版本

**Comment by finnome** [comment]
@leon332157 那我试看看新版本，谢谢哈

**Comment by finnome** [comment]
@leon332157 已经解决，谢谢哈。确实要iOS 11才能运行

**Comment by leon332157** [comment]
嗯嗯
