### ISSUE TITLE
已下载训练文件， nn_play.py报如下错

### ISSUE THREAD

**Issue by wangwanjie** [Prinsphield/Wechat_AutoJump#44]
我已经下载了训练文件并解压放于 resources 目录，安装了 openCV2和 openCV3，运行报如下错，第一句是 python 版本不匹配，那后面的呢：
/Users/CoderJay/tensorflow/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
2018-01-08 14:13:31.602251: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
WARNING:tensorflow:From nn_play.py:72: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
2018-01-08 14:13:32.962729: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962751: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962793: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962840: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962842: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962853: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962886: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962922: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.962960: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963019: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963040: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963075: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963116: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963144: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963174: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963195: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963245: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963246: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963343: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963366: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963402: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963418: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963533: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963569: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963595: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963625: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963636: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963669: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963685: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
2018-01-08 14:13:32.963720: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
Traceback (most recent call last):
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nn_play.py", line 206, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 48, in __init__
    self.load_resource()
  File "nn_play.py", line 77, in load_resource
    self.saver_coarse.restore(self.sess, self.ckpt)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "nn_play.py", line 206, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 48, in __init__
    self.load_resource()
  File "nn_play.py", line 75, in load_resource
    self.saver_coarse = tf.train.Saver(var_coarse)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Users/CoderJay/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

**Comment by Prinsphield** [comment]
有teamviewer吗，打开告诉我id和passwd，我给你看看？

**Comment by pkuanjie** [comment]
@Prinsphield 解决了吗

**Comment by Prinsphield** [comment]
@Richard-An 他还没告诉我id，还没看

**Comment by Imsiaocong** [comment]
同问，谷歌了几个没看明白

**Comment by Prinsphield** [comment]
@Imsiaocong 有teamviewer吗，打开告诉我id和passwd，我给你看看？

**Comment by Imsiaocong** [comment]
@Prinsphield 谢谢回复。不好意思，我这边晚了想睡了。我的报错基本和他一样，最后面也是Unsuccessful TensorSliceReader constructor: Failed to get matching files on resource/train_logs_coarse/best_model.ckpt-13999: Not found: resource/train_logs_coarse; No such file or directory

**Comment by Imsiaocong** [comment]
@Prinsphield  teamviewer弄好了
微信 wd1998313
有空的话加下微信吧，我好上线远程

**Comment by wangwanjie** [comment]
@Prinsphield 你好，我这两天工作没看github通知，这是我teamviewer id和password，你有空就连上，我一直开着：594 211 237，k7d86m

**Comment by Prinsphield** [comment]
@wangwanjie 我连了，你好像锁屏了

**Comment by wangwanjie** [comment]
@Prinsphield 我刚刚开会去了，不好意思！方便加个联系方式实时联系下么？我QQ:396736694.
