### ISSUE TITLE
显示错误，用虚拟机ubuntu连的，运行不了

### ISSUE THREAD

**Issue by ShilangChen1011** [Prinsphield/Wechat_AutoJump#49]
python play.py --phone Android --sensitivity 2.045
error: device not found
error: device not found
Traceback (most recent call last):
  File "play.py", line 175, in <module>
    AI.run()
  File "play.py", line 160, in run
    self.play()
  File "play.py", line 139, in play
    self.state = self.get_current_state()
  File "play.py", line 71, in get_current_state
    self.resolution = state.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Prinsphield** [comment]
你本身系统是什么？你usb没能读取手机啊

**Comment by ShilangChen1011** [comment]
ubuntu的，弄好了，谢谢了
