### ISSUE TITLE
运行报错，之前的版本没有这个问题～

### ISSUE THREAD

**Issue by badtoperfect** [Prinsphield/Wechat_AutoJump#51]
Wechat_AutoJump$ python play.py --phone Android --sensitivity 2.045
1674 KB/s (223267 bytes in 0.130s)
Traceback (most recent call last):
  File "play.py", line 174, in <module>
    AI.run()
  File "play.py", line 159, in run
    self.play()
  File "play.py", line 145, in play
    self.target_pos = self.get_target_position_fast(self.state, self.player_pos)
  File "play.py", line 111, in get_target_position_fast
    b1, b2 = cv2.connectedComponents(m)
AttributeError: 'module' object has no attribute 'connectedComponents'

**Comment by Prinsphield** [comment]
请用opencv 3

**Comment by badtoperfect** [comment]
OK,谢谢～
