### ISSUE TITLE
play.py里的import wda ？

### ISSUE THREAD

**Issue by smilexnan** [Prinsphield/Wechat_AutoJump#8]
import wda 是需要pip 吗？但是我pip install wda没有找到。

**Comment by Prinsphield** [comment]
git pull一下，现在没有了，你是Android的话不用wda

**Comment by smilexnan** [comment]
谢谢，我再试一下

**Comment by Jenner4S** [comment]
2018-01-26 11:21:41.290542: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX AVX2 FMA
==== successfully restored ====
Traceback (most recent call last):
  File "nn_play.py", line 209, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 50, in __init__
    import wda
ImportError: No module named wda

**Comment by Jenner4S** [comment]
ios真机测试

**Comment by Prinsphield** [comment]
readme里都写的很清楚了，参考这个安装https://testerhome.com/topics/7220

**Comment by leon332157** [comment]
@Prinsphield 我感觉还在安卓机方便，现在也在训练tensorflow，跳了800多分
😎
