### ISSUE TITLE
运行 python nn_play.py --phone Android --sensitivity 2.045 出错。

### ISSUE THREAD

**Issue by hoseynwnw** [Prinsphield/Wechat_AutoJump#81]
D:\master\Wechat_AutoJump-master>python nn_play.py --phone Android --sensitivity 2.045
Traceback (most recent call last):
  File "C:\Users\wc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 62, in preload_check
    ctypes.WinDLL(build_info.nvcuda_dll_name)
  File "C:\Users\wc\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nn_play.py", line 10, in <module>
    import tensorflow as tf
  File "C:\Users\wc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\wc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\wc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\wc\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 70, in preload_check
    % build_info.nvcuda_dll_name)
ImportError: Could not find 'nvcuda.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Typically it is installed in 'C:\Windows\System32'. If it is not present, ensure that you have a CUDA-capable GPU with the correct driver installed.

**Comment by Prinsphield** [comment]
你电脑没有GPU吧，那你装cpu的TensorFlow好了
