### ISSUE TITLE
ios刷榜成功

### ISSUE THREAD

**Issue by wangzidaren** [Prinsphield/Wechat_AutoJump#85]
iphone6sp刷榜成功

**Comment by CainLuo** [comment]
请问怎么捣鼓的

**Comment by Pcookie** [comment]
==== successfully restored ====
Traceback (most recent call last):
  File "nn_play.py", line 211, in <module>
    AI = WechatAutoJump(args.phone, args.sensitivity, args.serverURL, args.debug, args.resource)
  File "nn_play.py", line 50, in __init__
    import wda
ImportError: No module named wda


这个wda模块怎么导入？  是facebook的wda？？

**Comment by Prinsphield** [comment]
@Pcookie https://testerhome.com/topics/7220
